spring:
  application:
    name: ppixel-demo
  jpa:
    open-in-view: false

  # data source is not set. Please refer dev profile for local usage
  liquibase:
    enabled: true
    change-log: classpath:changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
