spring:
  application:
    name: ppixel-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/ppixel_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: db-changelog.xml
