ALTER TABLE email_data ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE phone_data ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "user" ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
